sonar.projectKey=alicalice_projeto-vende_ai

sonar.organization=alicalice

sonar.sources=backend/src,frontend

sonar.exclusions=**/node_modules/**,**/dist/**,.next/**

sonar.tests=backend

sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

